from .base_llm import BaseLLM
from .sft import test_model

import json
from .data import DATA_DIR
from .sft import TokenizedDataset
from peft import LoraConfig, get_peft_model
from transformers import TrainingArguments, Trainer

def load() -> BaseLLM:
    from pathlib import Path

    from peft import PeftModel

    model_name = "rft_model"
    model_path = Path(__file__).parent / model_name

    llm = BaseLLM()
    llm.model = PeftModel.from_pretrained(llm.model, model_path).to(llm.device)
    llm.model.eval()

    return llm

def format_rft_example(question: str, correct_answer: float, reasoning_chain: str) -> dict[str, str]:
    """
    In RFT, the 'answer' is the full reasoning path including the <answer> tags.
    """
    return {
        "question": question,
        "answer": reasoning_chain
    }

def train_model(
    output_dir: str,
    **kwargs,
):
    # Reuse much of the SFT code here
    #raise NotImplementedError()
    
    llm = BaseLLM()
    
    # Load the RFT data generated by datagen.py
    rft_path = DATA_DIR / "rft.json"
    with open(rft_path, "r") as f:
        raw_data = json.load(f)

    # Use the custom RFT formatter
    # raw_data format: [[question, answer, reasoning], ...]
    train_dataset = TokenizedDataset(
        llm.tokenizer, 
        raw_data, 
        lambda q, a, r: format_rft_example(q, a, r)
    )

    # LoRA Config - The README suggests a slightly larger adapter for RFT
    config = LoraConfig(
        r=8,
        lora_alpha=32, 
        target_modules="all-linear", 
        bias="none", 
        task_type="CAUSAL_LM"
    )
    llm.model = get_peft_model(llm.model, config)
    llm.model.enable_input_require_grads()

    training_args = TrainingArguments(
        output_dir=output_dir,
        per_device_train_batch_size=16,
        learning_rate=1e-4,
        num_train_epochs=3,
        gradient_checkpointing=True,
        logging_dir=output_dir,
        save_strategy="epoch",
        report_to="tensorboard"
    )

    trainer = Trainer(
        model=llm.model,
        args=training_args,
        train_dataset=train_dataset,
    )

    trainer.train()
    llm.model.save_pretrained(output_dir)

if __name__ == "__main__":
    from fire import Fire

    Fire({"train": train_model, "test": test_model, "load": load})
